# Generated by Django 4.1.3 on 2022-11-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conv_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(default='blue', max_length=200)),
                ('avatar', models.ImageField(default='media/avatar/default.png', upload_to='media/avatar/')),
                ('type', models.IntegerField(choices=[(1, 'user'), (2, 'group')], default='user')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=10000, null=True)),
                ('send_date', models.DateTimeField()),
                ('type', models.IntegerField(choices=[(1, 'sms'), (2, 'image'), (3, 'video'), (4, 'gif'), (5, 'vocal')], default='sms')),
                ('reaction', models.CharField(blank=True, max_length=10, null=True)),
                ('media_path', models.CharField(blank=True, max_length=10000, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversation')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='core.user'),
        ),
    ]
