# Generated by Django 4.1.3 on 2022-11-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
