# Generated by Django 4.1.3 on 2022-11-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_conversation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='mms_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sms_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'group')], default=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(1, 'sms'), (2, 'image'), (3, 'video'), (4, 'gif'), (5, 'vocal')], default=1),
        ),
    ]
