# Generated by Django 4.1.3 on 2023-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_message_message_id_message_mms_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_state', models.IntegerField(choices=[(0, 'Not started'), (1, 'Running'), (2, 'Terminated'), (3, 'Error')], default=0)),
                ('process_start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('process_end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
